/* Minimal XLSX writer for the registration export. It avoids an external CDN. */
window.RegistrationXlsx = (() => {
  const encoder = new TextEncoder();
  const crcTable = Array.from({length:256},(_,n)=>{let value=n;for(let bit=0;bit<8;bit++)value=(value&1)?(value>>>1)^0xedb88320:value>>>1;return value>>>0;});
  const crc32 = bytes => {let value=0xffffffff;for(const byte of bytes)value=(value>>>8)^crcTable[(value^byte)&255];return (value^0xffffffff)>>>0;};
  const uint16 = value => Uint8Array.of(value&255,(value>>>8)&255);
  const uint32 = value => Uint8Array.of(value&255,(value>>>8)&255,(value>>>16)&255,(value>>>24)&255);
  const join = parts => {const length=parts.reduce((total,part)=>total+part.length,0),output=new Uint8Array(length);let offset=0;for(const part of parts){output.set(part,offset);offset+=part.length;}return output;};
  const zip = files => {let offset=0;const entries=[],local=[];for(const [name,content] of files){const nameBytes=encoder.encode(name),data=encoder.encode(content),crc=crc32(data),header=join([uint32(0x04034b50),uint16(20),uint16(0),uint16(0),uint16(0),uint16(0),uint32(crc),uint32(data.length),uint32(data.length),uint16(nameBytes.length),uint16(0),nameBytes]);local.push(header,data);entries.push({nameBytes,crc,size:data.length,offset});offset+=header.length+data.length;}const centralBytes=join(entries.map(entry=>join([uint32(0x02014b50),uint16(20),uint16(20),uint16(0),uint16(0),uint16(0),uint16(0),uint32(entry.crc),uint32(entry.size),uint32(entry.size),uint16(entry.nameBytes.length),uint16(0),uint16(0),uint16(0),uint16(0),uint32(0),uint32(entry.offset),entry.nameBytes])));return join([...local,centralBytes,uint32(0x06054b50),uint16(0),uint16(0),uint16(entries.length),uint16(entries.length),uint32(centralBytes.length),uint32(offset),uint16(0)]);};
  const xml = value => String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]));
  const column = index => {let name='';while(index){const rem=(index-1)%26;name=String.fromCharCode(65+rem)+name;index=Math.floor((index-1)/26);}return name;};
  const sheet = rows => `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:H${Math.max(rows.length,1)}"/><sheetViews><sheetView workbookViewId="0"/></sheetViews><cols><col min="1" max="1" width="14.83203125" customWidth="1"/><col min="2" max="2" width="24.83203125" customWidth="1"/><col min="3" max="3" width="22.83203125" customWidth="1"/><col min="4" max="4" width="28.83203125" customWidth="1"/><col min="5" max="5" width="16.83203125" customWidth="1"/><col min="6" max="6" width="40.83203125" customWidth="1"/><col min="7" max="7" width="18.83203125" customWidth="1"/><col min="8" max="8" width="22.83203125" customWidth="1"/></cols><sheetData>${rows.map((row,rowIndex)=>`<row r="${rowIndex+1}">${row.map((value,columnIndex)=>{const ref=column(columnIndex+1)+(rowIndex+1);return typeof value==='number'?`<c r="${ref}"><v>${value}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`;}).join('')}</row>`).join('')}</sheetData></worksheet>`;
  const create = rows => new Blob([zip([
    ['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],
    ['_rels/.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],
    ['xl/workbook.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="HNKH" sheetId="1" r:id="rId1"/></sheets></workbook>'],
    ['xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'],
    ['xl/worksheets/sheet1.xml',sheet(rows)]
  ])],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
  return {create};
})();
